export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  SEGUIMIENTO: '/seguimiento',
  CALIDAD_DATOS: '/calidad-datos',
  JUGADORAS: '/jugadoras',
  JUGADORA_PROFILE: '/jugadoras/:id',
  WELLNESS: '/wellness',
  SESIONES: '/sesiones',
  PARTIDOS: '/partidos',
  CARGA_COMPETITIVA: '/carga-competitiva',
  LESIONES: '/lesiones',
  TESTS: '/tests',
  CMJ: '/pruebas-cmj',
  FUERZA: '/fuerza',
  PLANTILLAS_FUERZA: '/plantillas-fuerza',
  SEMANAL: '/semanal',
  ALERTAS: '/alertas',
  DECISION_DIARIA: '/decision-diaria',
  IMPORTAR: '/importar',
  TEMPORADAS: '/temporadas',
  SEGUIMIENTO_MENSTRUAL: '/seguimiento-menstrual',
} as const
